spring:
  datasource:
    url: jdbc:mysql://localhost:3306/somos_mas?serverTimezone=UTC
    username: username
    password: password
    driver-class: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    jwt:
      secret-key: secret-key
      expiration-length: 3600000

      
amazonProperties:
    accessKey: AKIA5YX3QC3YARN66KVE
    secretKey: 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


app:
  sengrid:
    key: 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
    emailIssuing: matias-leandro@outlook.com


